# Generated by Django 2.2.1 on 2019-07-10 18:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('EQuiz', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Questiontype',
            fields=[
                ('id', models.BigAutoField(db_column='ID', primary_key=True, serialize=False)),
                ('description', models.CharField(blank=True, db_column='Description', max_length=512, null=True)),
                ('code', models.CharField(db_column='Code', max_length=2042)),
                ('optionsrequired', models.IntegerField(db_column='OptionsRequired')),
                ('madeby', models.CharField(blank=True, db_column='MadeBy', max_length=129, null=True)),
                ('createdon', models.DateTimeField(blank=True, db_column='CreatedOn', null=True)),
                ('lastupdated', models.DateTimeField(blank=True, db_column='LastUpdated', null=True)),
            ],
            options={
                'db_table': 'QuestionType',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(db_column='ID', primary_key=True, serialize=False)),
                ('question', models.CharField(db_column='Question', max_length=512)),
                ('option1', models.CharField(db_column='Option1', max_length=512)),
                ('option2', models.CharField(db_column='Option2', max_length=512)),
                ('option3', models.CharField(blank=True, db_column='Option3', max_length=512, null=True)),
                ('option4', models.CharField(blank=True, db_column='Option4', max_length=512, null=True)),
                ('answeroption1', models.IntegerField(db_column='AnswerOption1')),
                ('answeroption2', models.IntegerField(db_column='AnswerOption2')),
                ('answeroption3', models.IntegerField(blank=True, db_column='AnswerOption3', null=True)),
                ('answeroption4', models.IntegerField(blank=True, db_column='AnswerOption4', null=True)),
                ('createdon', models.DateField(blank=True, db_column='CreatedOn', null=True)),
                ('lastupdated', models.DateField(blank=True, db_column='LastUpdated', null=True)),
                ('attachments', models.CharField(blank=True, db_column='Attachments', max_length=2024, null=True)),
                ('madeby', models.ForeignKey(blank=True, db_column='MadeBy', null=True, on_delete=django.db.models.deletion.CASCADE, to='EQuiz.AdminUsers')),
                ('type', models.ForeignKey(db_column='Type', on_delete=django.db.models.deletion.CASCADE, to='EQuiz.Questiontype')),
            ],
            options={
                'db_table': 'Question',
            },
        ),
    ]
