# Generated by Django 2.2.1 on 2019-07-31 07:01

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('EQuiz', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(db_column='Id', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='Name', max_length=129)),
                ('numberofquestions', models.IntegerField(blank=True, db_column='NumberOfQuestions')),
                ('duration', models.BigIntegerField(blank=True, db_column='Duration', null=True)),
                ('positivemarks', models.IntegerField(db_column='PositiveMarks', default=1)),
                ('negativemarks', models.IntegerField(db_column='NegativeMarks', default=0)),
                ('description', models.CharField(blank=True, db_column='Description', default='', max_length=1025, null=True)),
                ('difficultyratio', models.CharField(blank=True, db_column='DifficultyRatio', default='', max_length=64, null=True)),
                ('createdon', models.DateTimeField(blank=True, db_column='CreatedOn', default=datetime.datetime(2019, 7, 31, 12, 31, 1, 401766), null=True)),
            ],
            options={
                'db_table': 'Quiz',
                'managed': True,
            },
        ),
        migrations.RemoveField(
            model_name='questiontype',
            name='madeby',
        ),
        migrations.AlterModelOptions(
            name='adminuser',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='organisation',
            options={'managed': True},
        ),
        migrations.AlterField(
            model_name='adminuser',
            name='creationmode',
            field=models.CharField(db_column='CreationMode', max_length=17),
        ),
        migrations.AlterField(
            model_name='adminuser',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='adminuser',
            name='name',
            field=models.CharField(db_column='UserName', max_length=129, unique=True),
        ),
        migrations.AlterField(
            model_name='adminuser',
            name='organisationid',
            field=models.ForeignKey(db_column='Organisation', on_delete=django.db.models.deletion.DO_NOTHING, to='EQuiz.Organisation'),
        ),
        migrations.AlterField(
            model_name='adminuser',
            name='password',
            field=models.TextField(db_column='Password'),
        ),
        migrations.AlterField(
            model_name='adminuser',
            name='type',
            field=models.IntegerField(db_column='Type', default=1),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='creationmode',
            field=models.CharField(db_column='CreationMode', default='Website', editable=False, max_length=45),
        ),
        migrations.DeleteModel(
            name='Question',
        ),
        migrations.DeleteModel(
            name='Questiontype',
        ),
        migrations.AddField(
            model_name='quiz',
            name='createdby',
            field=models.ForeignKey(blank=True, db_column='CreatedBy', null=True, on_delete=django.db.models.deletion.CASCADE, to='EQuiz.AdminUser'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='organisation',
            field=models.ForeignKey(db_column='Organisation', on_delete=django.db.models.deletion.CASCADE, to='EQuiz.Organisation'),
        ),
    ]
