# Generated by Django 2.2.1 on 2019-06-30 19:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organisation',
            fields=[
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='Name', max_length=129)),
                ('country', models.CharField(blank=True, db_column='Country', max_length=32, null=True)),
                ('address', models.CharField(blank=True, db_column='Address', max_length=257, null=True)),
                ('representative', models.CharField(db_column='Representative', max_length=129)),
                ('mobile', models.CharField(blank=True, db_column='Mobile', max_length=15, null=True)),
                ('email', models.CharField(blank=True, db_column='Email', max_length=129, null=True)),
                ('type', models.CharField(db_column='Type', max_length=129)),
                ('createdon', models.DateField(blank=True, db_column='CreatedOn', null=True)),
                ('creationmode', models.CharField(blank=True, db_column='CreationMode', max_length=45, null=True)),
            ],
            options={
                'db_table': 'Organisation',
            },
        ),
        migrations.CreateModel(
            name='Adminusers',
            fields=[
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='Name', max_length=129, unique=True)),
                ('password', models.CharField(db_column='Password', max_length=129)),
                ('country', models.CharField(blank=True, db_column='Country', max_length=33, null=True)),
                ('address', models.CharField(blank=True, db_column='Address', max_length=257, null=True)),
                ('type', models.IntegerField(db_column='Type')),
                ('createdon', models.DateTimeField(blank=True, db_column='CreatedOn', null=True)),
                ('creationmode', models.CharField(db_column='CreationMode', max_length=17)),
                ('organisationid', models.ForeignKey(db_column='OrganisationId', on_delete=django.db.models.deletion.CASCADE, to='EQuiz.Organisation')),
            ],
            options={
                'db_table': 'AdminUsers',
            },
        ),
    ]
