# Generated by Django 2.2.1 on 2019-07-31 07:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QuizAdmin', '0002_auto_20190731_1231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizquestion',
            name='lastupdated',
            field=models.DateTimeField(blank=True, db_column='LastUpdated', default=datetime.datetime(2019, 7, 31, 12, 35, 25, 548702), editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='questiontype',
            name='lastupdated',
            field=models.DateTimeField(blank=True, db_column='LastUpdated', default=datetime.datetime(2019, 7, 31, 12, 35, 25, 545701), editable=False, null=True),
        ),
    ]
